"""enables nullable billing

Revision ID: 05af1d26117e
Revises: 846962e42c9d
Create Date: 2023-09-18 23:22:01.217289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05af1d26117e'
down_revision = '846962e42c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('billing_address',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('billing_address',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
