"""empty message

Revision ID: 14b46028641f
Revises: acf55dac2551
Create Date: 2024-09-02 23:12:38.725765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14b46028641f'
down_revision = 'acf55dac2551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=sa.VARCHAR(length=72),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('SUPER', 'MANAGER', 'GENERAL', name='role'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('SUPER', 'MANAGER', 'GENERAL', name='role'),
               nullable=True)
        batch_op.alter_column('pin',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=72),
               existing_nullable=True)

    # ### end Alembic commands ###
