"""empty message

Revision ID: 2b123a5d8648
Revises: 9aacd8a131a9
Create Date: 2024-05-15 12:45:36.440231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b123a5d8648'
down_revision = '9aacd8a131a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=False)

    # ### end Alembic commands ###
