"""Separates portion to own table for better stock and price handling, updates relationships between portion, product, and cart items accordingly

Revision ID: 340db5cf556c
Revises: 96ba75b7cf59
Create Date: 2024-08-07 11:38:58.980326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '340db5cf556c'
down_revision = '96ba75b7cf59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('SLICE', 'WHOLE', 'MINI', name='portion_size'), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('price >= 0', name='non_negative_price'),
    sa.CheckConstraint('stock >= 0', name='non_negative_stock'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portion_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'portions', ['portion_id'], ['id'])
        batch_op.drop_column('portion')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stock', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False))

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portion', postgresql.ENUM('SLICE', 'WHOLE', 'MINI', name='portion'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('portion_id')

    op.drop_table('portions')
    # ### end Alembic commands ###
