"""adds optimal stock to portion

Revision ID: 4a9f679690e5
Revises: 340db5cf556c
Create Date: 2024-08-13 19:45:40.727918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9f679690e5'
down_revision = '340db5cf556c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optimal_stock', sa.Integer(), nullable=False))
    
    op.execute('UPDATE portions SET optimal_stock = 10 WHERE optimal_stock IS NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portions', schema=None) as batch_op:
        batch_op.drop_column('optimal_stock')

    # ### end Alembic commands ###
