"""empty message

Revision ID: 581bbeebc24a
Revises: 38ef1ede21dc
Create Date: 2024-04-20 19:06:30.591414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '581bbeebc24a'
down_revision = '38ef1ede21dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.TIMESTAMP(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='task_status'), autoincrement=False, nullable=False))
        batch_op.drop_column('completed_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
