"""adds fields for saving stripe event info to user and order models

Revision ID: 741929bfed9a
Revises: 7bb261c79a3e
Create Date: 2023-10-18 02:35:29.350916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '741929bfed9a'
down_revision = '7bb261c79a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_id', sa.String(), nullable=True))
        batch_op.alter_column('payment_method',
               existing_type=postgresql.ENUM('CREDIT_CARD', 'PAYPAL', 'CASH', name='pay_method'),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=postgresql.ENUM('CREDIT_CARD', 'PAYPAL', 'CASH', name='pay_method'),
               nullable=False)
        batch_op.drop_column('stripe_payment_id')

    # ### end Alembic commands ###
