"""update order total price

Revision ID: 846962e42c9d
Revises: 65f617431163
Create Date: 2023-09-18 20:05:40.115825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846962e42c9d'
down_revision = '65f617431163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordered', sa.Boolean(), nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('ordered')

    # ### end Alembic commands ###
