"""adds ref to address used for order checkout, cascades item delete on order delete

Revision ID: 8dce2061d2c3
Revises: e3c3cea1e151
Create Date: 2023-10-23 23:47:29.425826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8dce2061d2c3'
down_revision = 'e3c3cea1e151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['shipping_address_id'])
        batch_op.create_foreign_key(None, 'addresses', ['shipping_address_id'], ['id'])
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', postgresql.ENUM('CREDIT_CARD', 'PAYPAL', 'CASH', name='pay_method'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('shipping_address_id')

    # ### end Alembic commands ###
