"""empty message

Revision ID: 91840f0a70d0
Revises: f4ffd520403c
Create Date: 2024-03-31 16:51:31.655896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91840f0a70d0'
down_revision = 'f4ffd520403c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
