"""empty message

Revision ID: 96ba75b7cf59
Revises: abbdf87a020f
Create Date: 2024-06-15 19:32:22.321568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ba75b7cf59'
down_revision = 'abbdf87a020f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('stripe_session_id')

    # ### end Alembic commands ###
