"""empty message

Revision ID: 9aacd8a131a9
Revises: b529efdc5458
Create Date: 2024-05-01 23:42:51.628981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aacd8a131a9'
down_revision = 'b529efdc5458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=72),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=sa.String(length=72),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
