"""empty message

Revision ID: acf55dac2551
Revises: 118ec14183e2
Create Date: 2024-09-02 23:00:30.806790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acf55dac2551'
down_revision = '118ec14183e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('password', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('password_expiration', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Enum('SUPER', 'MANAGER', 'GENERAL', name='role'), nullable=False))
        batch_op.alter_column('pin',
               existing_type=sa.VARCHAR(length=72),
               nullable=True)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('firebase_uid')
        batch_op.drop_column('pin_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_expiration', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('pin',
               existing_type=sa.VARCHAR(length=72),
               nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('password_expiration')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
