"""empty message

Revision ID: b529efdc5458
Revises: 6a43bdf00425
Create Date: 2024-04-30 14:58:19.200337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b529efdc5458'
down_revision = '6a43bdf00425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_admin_id_fkey', 'users', ['admin_id'], ['id'])

    # ### end Alembic commands ###
