"""updates user model to replace firebase auth

Revision ID: befc73f0a0cc
Revises: 4a9f679690e5
Create Date: 2024-08-29 23:18:59.048400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'befc73f0a0cc'
down_revision = '4a9f679690e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portions', schema=None) as batch_op:
        batch_op.alter_column('optimal_stock',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    with op.batch_alter_table('portions', schema=None) as batch_op:
        batch_op.alter_column('optimal_stock',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
