"""empty message

Revision ID: dc3997a52fdb
Revises: 445c066007d8
Create Date: 2023-11-10 23:45:31.512855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3997a52fdb'
down_revision = '445c066007d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('orders_shipping_address_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'addresses', ['shipping_address_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_shipping_address_id_fkey', 'addresses', ['shipping_address_id'], ['id'])
        batch_op.alter_column('shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
