"""fixes name discrepancies and adds as_dict to address model

Revision ID: e3c3cea1e151
Revises: 449e7b65fb75
Create Date: 2023-10-22 02:58:02.429933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c3cea1e151'
down_revision = '449e7b65fb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip', sa.String(length=10), nullable=False))
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('zip')

    # ### end Alembic commands ###
